# Generated by Django 5.0.1 on 2024-04-12 13:15

import django.db.models.deletion
import notification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('notification', '0002_postforspecificprovider_immediatenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='additional_details',
        ),
        migrations.AddField(
            model_name='post',
            name='service_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Giza', 'Giza'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan'), ('Damietta', 'Damietta'), ('Port Said', 'Port Said'), ('Suez', 'Suez'), ('Ismailia', 'Ismailia'), ('Faiyum', 'Faiyum'), ('Beni Suef', 'Beni Suef'), ('Minya', 'Minya'), ('Assiut', 'Assiut'), ('Sohag', 'Sohag'), ('Qena', 'Qena'), ('Red Sea', 'Red Sea'), ('New Valley', 'New Valley'), ('Matrouh', 'Matrouh'), ('Kafr El Sheikh', 'Kafr El Sheikh'), ('Monufia', 'Monufia'), ('Dakahlia', 'Dakahlia'), ('Sharqia', 'Sharqia'), ('North Sinai', 'North Sinai'), ('South Sinai', 'South Sinai'), ('Beheira', 'Beheira'), ('Gharbia', 'Gharbia'), ('Qalyubia', 'Qalyubia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[notification.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
