# Generated by Django 5.0.1 on 2024-04-12 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('notification', '0003_remove_post_additional_details_post_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
