# Generated by Django 5.0.1 on 2024-04-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('notification', '0004_alter_postnews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforspecificprovider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
