# Generated by Django 5.0.1 on 2024-04-19 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('notification', '0006_chatmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immediatenotification',
            old_name='related_post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='immediatenotification',
            name='is_from_provider',
        ),
        migrations.RemoveField(
            model_name='immediatenotification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='immediatenotification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='postforspecificprovider',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='postforspecificprovider',
            name='rejected',
        ),
        migrations.AddField(
            model_name='immediatenotification',
            name='provider_recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='account.providerprofile'),
        ),
        migrations.AddField(
            model_name='immediatenotification',
            name='user_recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='account.userprofile'),
        ),
        migrations.CreateModel(
            name='PostForSpecificProviderNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.postforspecificprovider')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.providerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
