# Generated by Django 5.0.1 on 2024-05-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_rename_related_post_immediatenotification_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
