# Generated by Django 5.0.1 on 2024-05-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_immediatenotification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immediatenotification',
            name='type',
            field=models.CharField(default='type 2', max_length=10, null=True),
        ),
    ]
