# Generated by Django 5.0.1 on 2024-05-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_alter_immediatenotification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immediatenotification',
            name='type',
        ),
    ]
