# Generated by Django 5.0.1 on 2024-04-04 15:51

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_password_token', models.CharField(blank=True, default='', max_length=50)),
                ('reset_password_expire', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Providerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[account.models.validate_phone_number])),
                ('ratings', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('role', models.CharField(default='service_provider', max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='user_images/%Y/%m/%d/', validators=[account.models.validate_image_extension])),
                ('profession', models.TextField(max_length=50)),
                ('fixed_salary', models.CharField(max_length=5)),
                ('id_image', models.ImageField(upload_to='id_images/%Y/%m/%d/', validators=[account.models.validate_image_extension])),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.providerprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[account.models.validate_phone_number])),
                ('role', models.CharField(default='customer', max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='user_images/%Y/%m/%d/', validators=[account.models.validate_image_extension])),
                ('provider_favourites', models.ManyToManyField(to='account.providerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images/%Y/%m/%d/', validators=[account.models.validate_image_extension])),
                ('provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.providerprofile')),
            ],
        ),
    ]
