# Generated by Django 5.0.1 on 2024-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(default='customer', max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='user_images/%Y/%m/%d/')),
            ],
        ),
    ]
