# Generated by Django 5.0.1 on 2024-04-25 22:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images/%Y/%m/%d/', validators=[account.models.validate_image_extension])),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
        migrations.AddField(
            model_name='work',
            name='images',
            field=models.ManyToManyField(to='account.image'),
        ),
    ]
