# Generated by Django 5.0.1 on 2024-02-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
