# Generated by Django 5.0.1 on 2024-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_userprofile_is_verified_userprofile_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_images/%Y/%m/%d/"
            ),
        ),
    ]
