# Generated by Django 5.0.1 on 2024-05-11 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userproviderfavourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproviderfavourite',
            old_name='provider',
            new_name='provider_favourite',
        ),
    ]
