# Generated by Django 5.0.1 on 2024-02-11 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_email_userprofile_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Providerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(default='customer', max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='user_images/%Y/%m/%d/')),
                ('profession', models.TextField(max_length=50)),
                ('fixed_salary', models.IntegerField()),
                ('id_image', models.ImageField(upload_to='id_images/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
