# Generated by Django 5.0.1 on 2024-02-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_providerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='fixed_salary',
            field=models.CharField(max_length=5),
        ),
    ]
