# Generated by Django 5.0.1 on 2024-02-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_providerprofile_fixed_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='role',
            field=models.CharField(default='service_provider', max_length=20),
        ),
    ]
