# Generated by Django 5.0.1 on 2024-02-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_providerprofile_ratings_review'),
        ('service', '0002_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
