# Generated by Django 5.0.1 on 2024-02-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_providerprofile_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='provider_favourites',
            field=models.ManyToManyField(to='account.providerprofile'),
        ),
    ]
