# Generated by Django 5.0.1 on 2024-03-06 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userprofile_provider_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images/%Y/%m/%d/')),
                ('provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.providerprofile')),
            ],
        ),
    ]
