# Generated by Django 5.0.1 on 2024-04-04 15:51

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name=1000)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', validators=[service.models.validate_image_extension])),
            ],
        ),
    ]
