# Generated by Django 5.0.1 on 2024-02-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifi', '0002_service_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[(1, 'Plumbing'), (2, 'Electricity'), (3, 'Painting'), (4, 'Carpentry'), (5, 'Cleaning Services'), (6, 'Ceramic')], max_length=255),
        ),
    ]
