# Generated by Django 5.0.1 on 2024-05-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifi', '0004_chatnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='type 1', max_length=10, null=True),
        ),
    ]
