# Generated by Django 5.0.1 on 2024-02-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifi', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='D:\\studying\\proj_new\\PROJECT\\servfix\\media\\post_images'),
        ),
    ]
